#!/bin/bash

if [ -d "deploydir" ]; then
	cd deploydir
	git pull
else
	git clone git@github.com:matt-h/matt-h.github.io.git deploydir
	cd deploydir
fi
rsync -av --delete --exclude ".git" ../output/. .
cp ../CNAME CNAME
git add -u
git add -A
git commit -a -m "Deploying new version"
git push
