[build]
command = "npm run prod"
publish = "build_production"

[[redirects]]
  from = "/*.html"
  to = "/:splat/"
  status = 301

[[redirects]]
  from = "/categories/*.html"
  to = "/blog/categories/:splat/"
  status = 301
